### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by rociac** [evaveskova/microverse_facebook#10]
Everything in the project looks great! The only suggestion is to move all the logic from the views to a helper file and making a post partial, this will make your code more readable and easy to maintain.

**Comment by rmauritsson** [comment]
The code presentation was great.
I think you should change the naming of the destroy links to delete

**Comment by KerronKing** [comment]
Good presentation Roy! The project is coming along great.

**Comment by noomdalv** [comment]
Looking good my friend @RoyNyaga, i can see a bright future ahead of you, keep it up!

**Comment by RoyNyaga** [comment]
> Looking good my friend @RoyNyaga, I can see a bright future ahead of you, keep it up!

Thanks, man, it's encouraging.
